/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlankFillQuestion: typeof import('./app_components/BlankFillQuestion.vue')['default']
    BlankFillQuestionContent: typeof import('./app_components/BlankFillQuestionContent.vue')['default']
    ChatbotWindow: typeof import('./app_components/ChatbotWindow.vue')['default']
    ExerciseSkeleton: typeof import('./app_components/test-details/ExerciseSkeleton.vue')['default']
    FormTestDetail: typeof import('./app_components/test-details/FormTestDetail.vue')['default']
    FormTestDetailAttempts: typeof import('./app_components/test-details/FormTestDetailAttempts.vue')['default']
    FormTestDetailQuestions: typeof import('./app_components/test-details/FormTestDetailQuestions.vue')['default']
    MLExercise: typeof import('./app_components/MLExercise.vue')['default']
    MLHbox: typeof import('./components/MLHbox.vue')['default']
    MLLoadingScreen: typeof import('./components/MLLoadingScreen.vue')['default']
    MLQuestion: typeof import('./app_components/MLQuestion.vue')['default']
    MLSkeleton: typeof import('./components/MLSkeleton.vue')['default']
    MLTextField: typeof import('./components/MLTextField.vue')['default']
    MLVbox: typeof import('./components/MLVbox.vue')['default']
    MultipleChoiceQuestion: typeof import('./app_components/MultipleChoiceQuestion.vue')['default']
    QuickExercisePanel: typeof import('./app_components/test-details/QuickExercisePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
