/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlankFillQuestion: typeof import('./app_components/BlankFillQuestion.vue')['default']
    BlankFillQuestionContent: typeof import('./app_components/BlankFillQuestionContent.vue')['default']
    ChatbotWindow: typeof import('./app_components/home_page/ChatbotWindow.vue')['default']
    copy: typeof import('./components/MLDateField copy.vue')['default']
    ExerciseSkeleton: typeof import('./app_components/test-details/ExerciseSkeleton.vue')['default']
    FormBookReservation: typeof import('./app_components/home_page/FormBookReservation.vue')['default']
    FormCustomerDetail: typeof import('./app_components/customer/FormCustomerDetail.vue')['default']
    FormCustomerList: typeof import('./app_components/customer/FormCustomerList.vue')['default']
    FormLogin: typeof import('./app_components/home_page/FormLogin.vue')['default']
    FormMenuDetail: typeof import('./app_components/menu/FormMenuDetail.vue')['default']
    FormMenuList: typeof import('./app_components/menu/FormMenuList.vue')['default']
    FormReservationDetail: typeof import('./app_components/reservation/FormReservationDetail.vue')['default']
    FormReservationList: typeof import('./app_components/reservation/FormReservationList.vue')['default']
    FormRestaurantInfo: typeof import('./app_components/home_page/FormRestaurantInfo.vue')['default']
    FormRestaurantMenu: typeof import('./app_components/home_page/FormRestaurantMenu.vue')['default']
    FormTestDetail: typeof import('./app_components/test-details/FormTestDetail.vue')['default']
    FormTestDetailAttempts: typeof import('./app_components/test-details/FormTestDetailAttempts.vue')['default']
    FormTestDetailQuestions: typeof import('./app_components/test-details/FormTestDetailQuestions.vue')['default']
    MLDateField: typeof import('./components/MLDateField.vue')['default']
    MLDialog: typeof import('./components/MLDialog.vue')['default']
    MLExercise: typeof import('./app_components/MLExercise.vue')['default']
    MLHbox: typeof import('./components/MLHbox.vue')['default']
    MLLoadingScreen: typeof import('./components/MLLoadingScreen.vue')['default']
    MLQuestion: typeof import('./app_components/MLQuestion.vue')['default']
    MLSkeleton: typeof import('./components/MLSkeleton.vue')['default']
    MLTextField: typeof import('./components/MLTextField.vue')['default']
    MLTimeField: typeof import('./components/MLTimeField.vue')['default']
    MLToastMessage: typeof import('./components/MLToastMessage.vue')['default']
    MLVbox: typeof import('./components/MLVbox.vue')['default']
    MultipleChoiceQuestion: typeof import('./app_components/MultipleChoiceQuestion.vue')['default']
    QuickExercisePanel: typeof import('./app_components/test-details/QuickExercisePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
