/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//tests': RouteRecordInfo<'//tests', '/tests', Record<never, never>, Record<never, never>>,
    '//tests/': RouteRecordInfo<'//tests/', '/tests', Record<never, never>, Record<never, never>>,
    '//tests/[testID]': RouteRecordInfo<'//tests/[testID]', '/tests/:testID', { testID: ParamValue<true> }, { testID: ParamValue<false> }>,
    '//tests/[testID]/attempts/': RouteRecordInfo<'//tests/[testID]/attempts/', '/tests/:testID/attempts', { testID: ParamValue<true> }, { testID: ParamValue<false> }>,
    '//tests/[testID]/attempts/[attemptID]': RouteRecordInfo<'//tests/[testID]/attempts/[attemptID]', '/tests/:testID/attempts/:attemptID', { testID: ParamValue<true>, attemptID: ParamValue<true> }, { testID: ParamValue<false>, attemptID: ParamValue<false> }>,
    '//tests/[testID]/questions': RouteRecordInfo<'//tests/[testID]/questions', '/tests/:testID/questions', { testID: ParamValue<true> }, { testID: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
