services:
  rasa:
    image: rasa/rasa:3.6.10
    ports:
      - 5005:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
      - ./data:/app/data
      - ./endpoints.yml:/app/endpoints.yml
    command:
      - run
      - --enable-api
      - --cors
      - "*"

  action_server:
    # image: rasa/rasa-sdk:latest
    build:
      context: ./actions
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
